- name: mkdir www
  file: path=/home/ec2-user/www state=directory owner=ec2-user group=ec2-user

- name: checkout repository
  git: repo=${repository} dest=/home/ec2-user/www/${application} version=master depth=1

- name: copy supervisord ini
  template: src=supervisord.ini.j2 dest=/etc/supervisord.d/${application}.ini
  sudo: yes

- name: add play2 application to supervisord
  supervisorctl: name=${application} state=present
  sudo: yes

- name: reload supervisord
  service: name=supervisord state=reloaded
  sudo: yes
