- name: install php
  yum: name=php state=latest
  sudo: true
- name: install php-mbstring
  yum: name=php state=latest
  sudo: true

- name: install php-mysql
  yum: name=php state=latest
  sudo: true

- name: install php-cli
  yum: name=php state=latest
  sudo: true

- name: restart apache2
  service: name=httpd state=restarted
  sudo: true
